name:                hspackage
version:             0.1.0.0
github:              "0cjs/hspackage"
license:             BSD3
author:              "Curt J. Sampson"
maintainer:          "cjs@cynic.net"
copyright:           "2019 Curt J. Sampson"
description:         Simple Stack package used to test _sastack

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hspackage-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspackage

tests:
  hspackage-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspackage
