name:                hspackage
version:             0.1.0.0
github:              "0cjs/hspackage"
license:             BSD3
author:              "Curt J. Sampson"
maintainer:          "cjs@cynic.net"
copyright:           "2019 Curt J. Sampson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/0cjs/hspackage#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hspackage-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspackage

tests:
  hspackage-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspackage
